import { doublePrecision, pgTable, uuid, varchar } from "drizzle-orm/pg-core";

export const patient = pgTable('t_patient', {
    t_patient_id: varchar('t_patient_id'),
    patient_hn: varchar('patient_hn'),
    f_patient_prefix_id: varchar('f_patient_prefix_id'),
    patient_firstname: varchar('patient_firstname'),
    patient_lastname: varchar('patient_lastname'),
    patient_xn: varchar('patient_xn'),
    f_sex_id: varchar('f_sex_id'),
    patient_birthday: varchar('patient_birthday'),
    patient_house: varchar('patient_house'),
    patient_road: varchar('patient_road'),
    patient_moo: varchar('patient_moo'),
    patient_tambon: varchar('patient_tambon'),
    patient_amphur: varchar('patient_amphur'),
    patient_changwat: varchar('patient_changwat'),
    f_patient_marriage_status_id: varchar('f_patient_marriage_status_id'),
    f_patient_occupation_id: varchar('f_patient_occupation_id'),
    f_patient_race_id: varchar('f_patient_race_id'),
    f_patient_nation_id: varchar('f_patient_nation_id'),
    f_patient_religion_id: varchar('f_patient_religion_id'),
    f_patient_education_type_id: varchar('f_patient_education_type_id'),
    f_patient_family_status_id: varchar('f_patient_family_status_id'),
    patient_father_firstname: varchar('patient_father_firstname'),
    patient_mother_firstname: varchar('patient_mother_firstname'),
    patient_couple_firstname: varchar('patient_couple_firstname'),
    patient_move_in_date_time: varchar('patient_move_in_date_time'),
    f_patient_discharge_status_id: varchar('f_patient_discharge_status_id'),
    patient_discharge_date_time: varchar('patient_discharge_date_time'),
    f_patient_blood_group_id: varchar('f_patient_blood_group_id'),
    f_patient_foreigner_id: varchar('f_patient_foreigner_id'),
    f_patient_area_status_id: varchar('f_patient_area_status_id'),
    patient_father_pid: varchar('patient_father_pid'),
    patient_mather_pid: varchar('patient_mather_pid'),
    patient_couple_pid: varchar('patient_couple_pid'),
    patient_community_status: varchar('patient_community_status'),
    patient_private_doctor: varchar('patient_private_doctor'),
    patient_pid: varchar('patient_pid'),
    patient_mother_lastname: varchar('patient_mother_lastname'),
    patient_father_lastname: varchar('patient_father_lastname'),
    patient_couple_lastname: varchar('patient_couple_lastname'),
    patient_phone_number: varchar('patient_phone_number').notNull(),
    f_patient_relation_id: varchar('f_patient_relation_id'),
    patient_contact_phone_number: varchar('patient_contact_phone_number'),
    patient_contact_sex_id: varchar('patient_contact_sex_id'),
    patient_contact_house: varchar('patient_contact_house'),
    patient_contact_moo: varchar('patient_contact_moo'),
    patient_contact_changwat: varchar('patient_contact_changwat'),
    patient_contact_amphur: varchar('patient_contact_amphur'),
    patient_contact_tambon: varchar('patient_contact_tambon'),
    patient_contact_road: varchar('patient_contact_road'),
    patient_contact_firstname: varchar('patient_contact_firstname'),
    patient_contact_lastname: varchar('patient_contact_lastname'),
    patient_birthday_true: varchar('patient_birthday_true'),
    patient_merged: varchar('patient_merged'),
    patient_record_date_time: varchar('patient_record_date_time'),
    patient_update_date_time: varchar('patient_update_date_time'),
    patient_staff_record: varchar('patient_staff_record'),
    patient_staff_modify: varchar('patient_staff_modify'),
    patient_staff_cancel: varchar('patient_staff_cancel'),
    patient_active: varchar('patient_active'),
    patient_drugallergy: varchar('patient_drugallergy'),
    patient_language_for_print: varchar('patient_language_for_print'),
    patient_patient_mobile_phone: varchar('patient_patient_mobile_phone'),
    patient_contact_mobile_phone: varchar('patient_contact_mobile_phone'),
    patient_has_home_in_pcu: varchar('patient_has_home_in_pcu'),
    t_health_family_id: varchar('t_health_family_id'),
    patient_other_country_address: varchar('patient_other_country_address'),
    patient_is_other_country: varchar('patient_is_other_country'),
    deny_allergy: varchar('deny_allergy'),
    latitude: doublePrecision('latitude'),
    longitude: doublePrecision('longitude'),
    t_person_id: varchar('t_person_id'),
    patient_patient_email: varchar('patient_patient_email'),
    patient_contact_email: varchar('patient_contact_email'),
    sent_email_invitation: varchar('sent_email_invitation'),
    welfare_old_hn: varchar('welfare_old_hn'),
    patient_postcode: varchar('patient_postcode'),
    patient_contact_postcode: varchar('patient_contact_postcode'),
    patient_addrees_eng: varchar('patient_addrees_eng'),
    patient_guid: uuid('patient_guid'),
    picture_profile: varchar('picture_profile')
})

export type SelectPatient = typeof patient.$inferSelect
export type InsertPatine = typeof patient.$inferSelect

export interface PatientModel {
    t_patient_id: string;
    patient_hn: string;
    f_patient_prefix_id: string;
    patient_firstname: string;
    patient_lastname: string;
    patient_xn: string;
    f_sex_id: string;
    patient_birthday: string;
    patient_house: string;
    patient_road: string;
    patient_moo: string;
    patient_tambon: string;
    patient_amphur: string;
    patient_changwat: string;
    f_patient_marriage_status_id: string;
    f_patient_occupation_id: string;
    f_patient_race_id: string;
    f_patient_nation_id: string;
    f_patient_religion_id: string;
    f_patient_education_type_id: string;
    f_patient_family_status_id: string;
    patient_father_firstname: string;
    patient_mother_firstname: string;
    patient_couple_firstname: string;
    patient_move_in_date_time: string;
    f_patient_discharge_status_id: string;
    patient_discharge_date_time: string;
    f_patient_blood_group_id: string;
    f_patient_foreigner_id: string;
    f_patient_area_status_id: string;
    patient_father_pid: string;
    patient_mather_pid: string;
    patient_couple_pid: string;
    patient_community_status: string;
    patient_private_doctor: string;
    patient_pid: string;
    patient_mother_lastname: string;
    patient_father_lastname: string;
    patient_couple_lastname: string;
    patient_phone_number: string;
    f_patient_relation_id: string;
    patient_contact_phone_number: string;
    patient_contact_sex_id: string;
    patient_contact_house: string;
    patient_contact_moo: string;
    patient_contact_changwat: string;
    patient_contact_amphur: string;
    patient_contact_tambon: string;
    patient_contact_road: string;
    patient_contact_firstname: string;
    patient_contact_lastname: string;
    patient_birthday_true: string;
    patient_merged: string;
    patient_record_date_time: string;
    patient_update_date_time: string;
    patient_staff_record: string;
    patient_staff_modify: string;
    patient_staff_cancel: string;
    patient_active: string;
    patient_drugallergy: string;
    patient_language_for_print: string;
    patient_patient_mobile_phone: string;
    patient_contact_mobile_phone: string;
    patient_has_home_in_pcu: string;
    t_health_family_id: string;
    patient_other_country_address: string;
    patient_is_other_country: string;
    deny_allergy: string;
    latitude: number;
    longitude: number;
    t_person_id: string;
    patient_patient_email: string;
    patient_contact_email: string;
    sent_email_invitation: string;
    welfare_old_hn: string;
    patient_postcode: string;
    patient_contact_postcode: string;
    patient_addrees_eng: string;
    patient_guid: string;
    picture_profile: string;
}